language: node_js
node_js:
- '4'
script:
- set -e
- npm run test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/as-table.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: gwE78DGcdK53bVCYFq1b7GLIWrfpT0WHi0anij6Vhcm8OEKrMEWyr1v9W0cBh5rYfJOR2NDPNVwk7zVtRBPSYv20rz6dF/Bj/6ZW+/hdmpyyoh2u0MSvuCp6MmA6eKKNZH11mj5aPYFbaGXdj+IHahOTSdpvXOyPv4/F56H0mUA7xCbCmwR81HUVdEFPiRBAaJE6hvEg+B01y/GLycBC+Bar1vZkVGbv30QKRCH5XyE297lNGovLhZaJ6eNEdUnpqYaNaIgobSuqBH1eSXf37tihTHoWUMU8Kwnga5Z0NrTAekaSRUjgfjH/0p1IkWOXOObqvmuvhVvCWs3M5E3NKgjYlbQwa28IIgkgmGnImf3ZCt3J5OhDTkECnQy0nrjl0jqcyd/lwkNN1EPct0VxUEi/rRfDquuZ6HWXC2mJEpmOKxfQRTYV3ZtQhnU/JnIUyIojKSXGxFIOtfUesGqpmHIbTrMv6i3C6i2iA4W8jIvwvCfwhOjiIcD/Gda5smhrjMosiFi2Fx/yz57Z4CyRL0mgEffolJmdpDgwAt/TBahsQ0a27LsBwCHPfS0TUFUnDhwUmEq5J01lQQsqN37uDsQVmpM5KOonpoMv3mcWEmPh/ifLMQIM0TrKgJm/bm7cDTABepW0AvKJEm3WFTzIgSS5Q1MKhamL69vhdKa4g1Q=
env:
  global:
  - secure: qChTSsDPSb/66GE07rn3FMdmiDRsjXNLUey9/UyRprWQSobBRvF95DessQPmLttSSldIH3QwcCZOvaCFPQcrdOYXUQ23rfCjf0WGMOQ4wIL/cXZWW3e/QsAbfPKKSdwb34Umk7K2cxPhuapeAPotf5Br24rGDDPYsld4ogF1WkCb+syBaYjfFz/WxL2Wbk08KZ37aLyJfQEMk7R4pI6KsKmtCylm+zTbhkwjz/2bnKqC4i4sjZJzoEvXmYAJE5q/AspSctgFDPoF3kZ0/tc293AhAbZpY5onq7b6j0oeKxwzXzCH0NyGvCjlBw5kOeau/2SMNUWHkGU3yuspDQ1gBuDjrMVMEspaJnov5CSvNz/VobrX0w1rvLIrWtsLNBwRsCLctZW4DSHe9cntlUqQYGX+Ii762MUNi4mHk5TSl2Ftu8ssOP8o5b+EDa+XDtJ7IddYRz1mrpBV3t2vs/x31w9GOopVe7qgcoGgIR4nRVemlm8Y8yGdLDQimD53IREiiZZTadU5rf0pBBFYuTv28Kdp7UMk8iAc+lgvmon3oEvrDD133GZVW4vgBQtn+kyk31hDqY8rsNxroYPthppQG8xo8vVYSfZrleQ0r9cXp6CTr54ksiUS9fSOsJsOTRyidQlXinp2CiURx3tVdynnXJo/G3/5tVvEKLZgLqJ2dQU=
