language: node_js
node_js:
  - "node"
script:
  - npm run lint
  - npm run lint-test
  - npm test
after_success: npm run coverage
deploy:
  provider: npm
  email: "rocket.mind@gmail.com"
  api_key:
    secure: QNFnaKIkbbcCuAqO1MkCxmgP7wXUlO6+G6GI56MD+Pg+mRdAHTSuNly8e9LOGioka4ouFBpDSBTuFsHNsoVvrtONzWALajloglewjGth8NaszQ2+8STAC5QdL+L2OokqTB8LU1C7CgZJTQBbGODRMET8O5iYUYbYebar15hTudgXJOKT4irh9/NN9LyOJl993VOXDSOLDhos8pM2n5hTIexotoHGTvurXI7BEwPKPwpCXk2wHuOuAXERfC5h8zvxjvQGJssGuYIFjLl+V8JYsjUS3b7doyGdokv+jUfX6R15i55eXG2dLZApkvXhEvHETN/FtrebfnVIntfZlOVElHQY8xhud4grxQMSD8yOGTA+K16j7k/5ZfBye9qRMcNDynXh2jA7epw0EvNUuiyHlqnqxEXnMbrWhdxfTw9eESZ1wzEFvKty8VFBHX9SZAfIqm3W2Job7Kd4RJD+bVXDdRcExBPdcuuuyUJaMhNc6maulmb5vBFsZw/xnqH1rOYJeXefDrvl7oSBIHTDWrXs3eFC/hTp7GnE7drVTDgbIAiViPefULIm8Jj6pGLG7WKQKfVo4X21o6iXhLOgYWbWwdRFR4rYZFK2IFn4rlHimZr/axGtvxwOVzjZKWNOOWLx1jbtutcJsZzvS3qjXCxnrpIKsNeJqdPYZ7u20dpaA8g=
