language: node_js
node_js:
- node
script:
- npm run lint
- npm run lint-test
- npm test
after_success: npm run coverage
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: arKawgGrXQDVvc4Dr3iceQHgOmHbHaNBXlOJGzZhCUeIcfLHbFiAtk0r5qBSUoRNtB/wZCJYZUk5hDtGFjnrtJa6GZmLg8EZmAgq1JlOzuXcPgTXkPL51mkUj4xzeuqUZ2ywvpOQnxPJ0lIdrH7dA7PgSsu0XG+G0kHOGy6w8GW/gykz1CrkKN1NlAaCvPpY7lYr/xJQ51OIVVOwjseDRL2LBshLZcdxzH1pkZWmvCqCwz/M40ELHPTL1hEUpc4YXMXw1LaNumTVvRxLcScyZ7YpFdgef3+AQosmNOCgYUwyRPr5RmTEs7CypCS4UbtmBJDnJuwDBVC5ZfesVo5U1553y9I2vLE5nQxqJnsjWUjmgsWPGBLbgo7O5Gw+x3M2mKvUKJ/E6U+rG/BA240pcHJeCLwHKZlU1qeYKH6/Oec++/mWKIOElx05/bZDhSvJhHdwKSeVRhPEJXygiim0u6ZK+H5868bo76O1J3Aib/Ap4ir01gjAWSrrR5rdyUnPcZuSs4Ka4raVYxwSaeMyLLcVMjmWjeS6nHF5tSd0md9UW1YRIPGgl6vN7Kp+pld+QmlT7+/E+Yuqa2ZRxb+flw5ccHH/2Dg71hrr2iOCQSPF9N1HO08NeEmaRrB7F/xsdvY1iZQp31gyVB7i+/P8oox89g06rDn0ApS6i7NnQoY=
